import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Check, ChevronLeft, ChevronRight, Clock3, FileSearch, Fingerprint, History, ImagePlus, LoaderCircle, LockKeyhole, Plus, ScanLine, Search, ShieldCheck, Upload, X } from 'lucide-react';
import { api, apiUrl, label } from './api';
import Report from './Report';
import type { Analysis, AuditEvent, Chain, DecisionPayload, HistoryItem } from './types';

function UploadCard({title,hint,file,onFile}:{title:string;hint:string;file:File|null;onFile:(file:File|null)=>void}) {
  const [url,setUrl] = useState('');
  useEffect(()=>{if(!file){setUrl('');return;}const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file]);
  return <div className="upload-wrap"><div className="upload-title"><b>{title}</b>{file&&<button aria-label={`Remove ${title}`} className="icon-button" onClick={()=>onFile(null)}><X size={15}/></button>}</div><label className={`upload ${file?'has-file':''}`}>
    <input type="file" accept="image/jpeg,image/png,image/webp" aria-label={title} onChange={e=>{onFile(e.target.files?.[0] || null);e.target.value='';}}/>
    {url?<img src={url} alt={`${title} preview`}/>:<><span className="upload-icon"><ImagePlus size={25}/></span><b>Choose an image</b><span>{hint}</span><span className="small">JPEG, PNG or WebP · up to 10 MB</span></>}
  </label>{file&&<div className="filename"><Check size={13}/><span>{file.name}</span><small>{(file.size/1024/1024).toFixed(2)} MB</small></div>}</div>;
}

export default function App() {
  const [page,setPage] = useState<'screening'|'history'|'audit'>('screening');
  const [actor,setActor] = useState('DEMO-01');
  const [document,setDocument] = useState<File|null>(null);const [live,setLive] = useState<File|null>(null);
  const [date,setDate] = useState('2026-10-03'); const [kind,setKind] = useState('passport');const [region,setRegion] = useState('');
  const [scenario,setScenario] = useState('genuine');const [loadingSample,setLoadingSample] = useState(false);
  const [busy,setBusy] = useState(false);const [seconds,setSeconds] = useState(0);const [error,setError] = useState('');
  const [analysis,setAnalysis] = useState<Analysis|null>(null);const [record,setRecord] = useState<HistoryItem|null>(null);
  const [scanRequest,setScanRequest] = useState(crypto.randomUUID());
  const [retryLocked,setRetryLocked] = useState(false);const submission = useRef<{data:FormData;actor:string;key:string}|null>(null);
  const [history,setHistory] = useState<{items:HistoryItem[];total:number;offset:number}>({items:[],total:0,offset:0});
  const [query,setQuery] = useState('');const [filter,setFilter] = useState('');const [historyBusy,setHistoryBusy] = useState(false);
  const historyController = useRef<AbortController|null>(null);
  const [chain,setChain] = useState<Chain|null>(null);const [checking,setChecking] = useState(false);
  const [apiReady,setApiReady] = useState<boolean|null>(null);
  const [deploymentWarning,setDeploymentWarning] = useState('');
  useEffect(()=>{api<{ocr_available:boolean;audit_persistent:boolean}>('/health').then(health=>{setApiReady(true);const gaps=[];if(!health.ocr_available)gaps.push('OCR is unavailable');if(!health.audit_persistent)gaps.push('review history is temporary');setDeploymentWarning(gaps.length?`${gaps.join(' and ')} on this backend. Connect the Docker backend for the complete demo.`:'');}).catch(()=>setApiReady(false));},[]);
  useEffect(()=>{if(!busy)return;const start=Date.now();setSeconds(0);const timer=setInterval(()=>setSeconds(Math.floor((Date.now()-start)/1000)),1000);return()=>clearInterval(timer);},[busy]);
  useEffect(()=>()=>historyController.current?.abort(),[]);
  function newRequest(){setScanRequest(crypto.randomUUID());setError('');}
  async function loadSample(){setLoadingSample(true);setError('');try{
    const images = await Promise.all(['document','live'].map(async part=>{const response=await fetch(apiUrl(`/demo/fixtures/${scenario}/${part}`));if(!response.ok)throw new Error('Could not load synthetic fixtures. Check the API and bundled portrait asset.');return new File([await response.blob()],`synthetic_${scenario}_${part}.png`,{type:'image/png'});}));
    setDocument(images[0]);setLive(images[1]);setDate('2026-10-03');setKind('passport');setRegion('[0.75,0.21,0.19375,0.46]');newRequest();
  }catch(e){setError((e as Error).message);}finally{setLoadingSample(false);}}
  async function analyze(){if(!document)return;setError('');
    if(!retryLocked){
      if(document.size>10*1024**2||(live&&live.size>10*1024**2)){setError('Each image must be at most 10 MiB.');return;}
      if(!/^[A-Za-z0-9_-]{3,64}$/.test(actor)){setError('Enter a valid demo officer label (3–64 letters, digits, _ or -).');return;}
      if(!date){setError('Select a reference date.');return;}
      if(region){try{const r=JSON.parse(region);if(!Array.isArray(r)||r.length!==4||r.some(x=>typeof x!=='number'||!Number.isFinite(x)))throw new Error();}catch{setError('Portrait region must be a JSON array of four numbers.');return;}}
      const data=new FormData();data.set('document',document);if(live)data.set('live',live);data.set('reference_date',date);data.set('document_type',kind);if(region)data.set('photo_region',region);
      submission.current={data,actor,key:scanRequest};
    }
    const pending=submission.current;if(!pending)return;setBusy(true);setRetryLocked(true);
    try{const response=await api<{analysis:Analysis|null;scan_event:AuditEvent;replayed:boolean}>('/scans/analyze',{method:'POST',headers:{'X-Officer-ID':pending.actor,'Idempotency-Key':pending.key},body:pending.data});setAnalysis(response.analysis);setRecord({scan:response.scan_event,latest_decision:null,latest_event_hash:response.scan_event.event_hash});setRetryLocked(false);submission.current=null;setScanRequest(crypto.randomUUID());setChain(null);}
    catch(e){setError(`${(e as Error).message} You can retry the same request safely.`);}finally{setBusy(false);}
  }
  async function loadHistory(offset=0){historyController.current?.abort();const controller=new AbortController();historyController.current=controller;setHistoryBusy(true);setError('');try{const params=new URLSearchParams({q:query,limit:'10',offset:String(offset)});if(filter)params.set('decision',filter);const data=await api<{items:HistoryItem[];total:number;offset:number}>(`/scans?${params}`,{signal:controller.signal});setHistory(data);}catch(e){if(!controller.signal.aborted)setError((e as Error).message);}finally{if(!controller.signal.aborted)setHistoryBusy(false);}}
  async function openScan(item:HistoryItem){setError('');try{const data=await api<{events:AuditEvent[];latest_event_hash:string}>(`/scans/${item.scan.scan_id}`);const last=data.events.filter(e=>e.kind==='decision').at(-1) as AuditEvent<DecisionPayload>|undefined;setRecord({scan:data.events[0],latest_decision:last||null,latest_event_hash:data.latest_event_hash});setAnalysis(null);setPage('screening');}catch(e){setError((e as Error).message);}}
  async function verify(){setChecking(true);setError('');try{setChain(await api<Chain>('/audit/verify'));}catch(e){setError((e as Error).message);setChain(null);}finally{setChecking(false);}}
  function exportCheckpoint(){if(!chain?.valid)return;const blob=new Blob([JSON.stringify({anchor_seq:chain.head_seq,anchor_hash:chain.head_hash,exported_at:new Date().toISOString()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=window.document.createElement('a');a.href=url;a.download='sentinel-audit-checkpoint.json';a.click();URL.revokeObjectURL(url);}
  function navigate(next:typeof page){setPage(next);setError('');if(next==='history')void loadHistory(0);if(next==='audit')void verify();}
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('screening');}}><span><ScanLine size={25}/></span>sentinel<span className="brand-dot">.</span></a><div className="workspace-label">DOCUMENT INTELLIGENCE</div><nav aria-label="Main navigation"><button className={page==='screening'?'active':''} onClick={()=>navigate('screening')}><FileSearch size={19}/>Screening workspace</button><button className={page==='history'?'active':''} onClick={()=>navigate('history')}><History size={19}/>Review history</button><button className={page==='audit'?'active':''} onClick={()=>navigate('audit')}><Fingerprint size={19}/>Audit integrity</button></nav><div className="sidebar-note"><ShieldCheck size={23}/><b>Evidence supports judgment.</b><p>This prototype never makes an automatic border decision.</p></div><div className="officer"><span className="avatar">DO</span><label>DEMO OFFICER<input aria-label="Demo officer label" value={actor} disabled={busy||retryLocked} onChange={e=>setActor(e.target.value)} maxLength={64}/></label></div><span className="small sidebar-muted">Local label · not authenticated</span></aside>
    <main><header className="topbar"><span>Operations <ChevronRight size={14}/> {page==='screening'?'Document review':page==='history'?'Review history':'Audit integrity'}</span><div><span className={`status-dot ${apiReady===false?'offline':''}`}/>{apiReady===null?'Connecting':apiReady?'Local API connected':'API unavailable'}<span className="demo-badge">SYNTHETIC DEMO</span></div></header><div className="main-content">
      <div className="page-heading"><div><p className="eyebrow">{page==='screening'?'OFFICER WORKSPACE':page==='history'?'TRACEABLE REVIEWS':'TAMPER-EVIDENT RECORDS'}</p><h1>{page==='screening'?'Review with context.':page==='history'?'A record of every review.':'Trust, with a trail.'}</h1><p>{page==='screening'?'Read the evidence. Understand the gaps. Make an informed decision.':page==='history'?'Search scan references, document hashes and officer labels.': 'Verify the sequence of recorded scans and human decisions.'}</p></div>{page==='screening'&&record&&<button className="button secondary" disabled={busy} onClick={()=>{setRecord(null);setAnalysis(null);setError('');}}><Plus size={17}/>New review</button>}</div>
      {deploymentWarning&&<div className="deployment-warning" role="status">{deploymentWarning}</div>}
      {error&&<div role="alert" className="error global-error">{error}<button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
      {page==='screening'&&<>{!record&&<div className="intake-grid"><section className="card intake"><div className="card-heading"><div><span className="step-label">01 / CAPTURE</span><h2>Start a document review</h2></div><span className="badge neutral"><LockKeyhole size={12}/>Images not retained</span></div><fieldset disabled={busy||retryLocked||loadingSample}><div className="upload-grid"><UploadCard title="Document image" hint="Identity or travel document" file={document} onFile={f=>{setDocument(f);newRequest();}}/><UploadCard title="Face reference" hint="Optional reference image" file={live} onFile={f=>{setLive(f);newRequest();}}/></div><div className="form-row"><label className="field">Document type<select value={kind} onChange={e=>{setKind(e.target.value);newRequest();}}>{['passport','visa','id','license','permit','unknown'].map(k=><option key={k} value={k}>{label(k)}</option>)}</select></label><label className="field">Reference date<input type="date" value={date} onChange={e=>{setDate(e.target.value);newRequest();}}/></label></div><details><summary>Portrait region (optional)</summary><label className="field"><span className="small muted">Normalized [x, y, width, height] on the original image. Excludes portrait from OCR.</span><input aria-label="Portrait region" value={region} placeholder="[0.75, 0.21, 0.19375, 0.46]" onChange={e=>{setRegion(e.target.value);newRequest();}}/></label></details></fieldset>
        <div className="intake-footer"><p><LockKeyhole size={14}/>Only scores, document hash and review metadata are recorded.</p><button className="button primary" onClick={analyze} disabled={!document||busy||loadingSample}>{busy?<><LoaderCircle className="spin" size={17}/>Analyzing · {seconds}s</>:retryLocked?<>Retry same scan<ArrowRight size={17}/></>:<>Analyze & record<ArrowRight size={17}/></>}</button></div>{busy&&<div role="status" className="running"><div className="running-line"/><p>Preparing OCR, validation, tampering and face evidence. The first scan may take longer.</p></div>}{retryLocked&&!busy&&<button className="text-button" onClick={()=>{setRetryLocked(false);submission.current=null;newRequest();}}>Unlock inputs for a new request (previous request may already be recorded)</button>}</section>
        <aside className="intake-aside"><section className="demo-card"><span className="eyebrow">TAKE A TEST FLIGHT</span><div className="sample-graphic"><div className="mock-card"><div className="mock-lines"><i/><i/><i/><i/></div><ScanLine size={36}/><span>SYNTHETIC / UTO</span></div><span className="sample-check"><Check size={18}/></span></div><h3>Explore a synthetic case</h3><p>Fictional documents and generated portraits. No real identities.</p><select aria-label="Synthetic scenario" value={scenario} disabled={busy||retryLocked||loadingSample} onChange={e=>setScenario(e.target.value)}><option value="genuine">Genuine-looking mock</option><option value="dob_altered">Altered date of birth</option><option value="photo_replaced">Replaced document photo</option><option value="wrong_face">Different face</option><option value="blacklisted">Mock blacklist hit</option><option value="blurred">Blurred capture</option></select><button className="button secondary full" disabled={busy||retryLocked||loadingSample} onClick={loadSample}>{loadingSample?'Loading…':'Load synthetic sample'}<ArrowRight size={16}/></button></section><section className="how-it-works"><span className="eyebrow">YOUR REVIEW, THREE STEPS</span>{[['01','Capture the evidence','Upload a document and face reference.'],['02','Inspect the signals','Compare fields, heatmaps and evidence gaps.'],['03','Record your judgment','Append a reasoned officer decision.']].map(([n,t,d])=><div key={n}><span>{n}</span><section><b>{t}</b><p>{d}</p></section></div>)}</section></aside></div>}
        {record&&<Report key={record.scan.scan_id+record.latest_event_hash} event={record.scan} analysis={analysis} actor={actor} initialDecision={record.latest_decision} initialHash={record.latest_event_hash} onRecorded={()=>setChain(null)}/>}
      </>}
      {page==='history'&&<section className="card history-card"><form className="searchbar" onSubmit={e=>{e.preventDefault();void loadHistory(0);}}><div><Search size={18}/><input aria-label="Search history" placeholder="Scan ID, document hash or officer label" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Decision filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All decisions</option>{['pending','approve','secondary_inspection','reject'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select><button className="button primary" disabled={historyBusy}>Search</button></form><div className="table-wrap"><table><thead><tr><th>Scan / timestamp</th><th>Document hash</th><th>Observed score</th><th>Officer decision</th><th/></tr></thead><tbody>{history.items.map(item=><tr key={item.scan.scan_id}><td><b>{item.scan.scan_id.slice(0,8)}</b><small>{new Date(item.scan.timestamp).toLocaleString()}</small></td><td><code>{item.scan.document_hash.slice(0,16)}…</code><small>{item.scan.actor}</small></td><td><b>{item.scan.payload.risk.score?.toFixed(2) ?? '—'}</b><small>{item.scan.payload.risk.category || 'Incomplete evidence'}</small></td><td><span className="badge neutral">{label(item.latest_decision?.payload.decision || 'pending')}</span></td><td><button className="text-button" onClick={()=>openScan(item)}>Open<ArrowRight size={14}/></button></td></tr>)}</tbody></table></div>{historyBusy?<p className="empty-small" role="status">Loading verified history…</p>:!history.items.length&&<div className="empty-small"><History size={32}/><h3>No matching reviews</h3><p>Recorded scans will appear here. Try a new scan or a different filter.</p></div>}<div className="pagination"><span>{history.total} recorded scans</span><div><button aria-label="Previous page" disabled={historyBusy||history.offset===0} onClick={()=>loadHistory(Math.max(0,history.offset-10))}><ChevronLeft size={18}/></button><span>{history.total?history.offset+1:0}–{Math.min(history.offset+10,history.total)}</span><button aria-label="Next page" disabled={historyBusy||history.offset+10>=history.total} onClick={()=>loadHistory(history.offset+10)}><ChevronRight size={18}/></button></div></div></section>}
      {page==='audit'&&<div className="audit-layout"><section className="card"><span className="audit-icon"><Fingerprint size={36}/></span><h2>{checking?'Checking the chain…':chain?.valid?'Recorded chain is intact':chain?'Integrity check failed':'Verification unavailable'}</h2><p className="muted">Each scan and decision is linked to the previous event by its content hash.</p>{chain?.valid?<><div className="metrics"><div><span>Verified events</span><strong>{chain.event_count}</strong></div><div><span>Head sequence</span><strong>{chain.head_seq}</strong></div></div><label className="field">Current head hash<code className="hash-block">{chain.head_hash}</code></label></>:chain&&<div role="alert" className="error">{chain.error} at sequence {chain.failed_seq}. History and writes are blocked.</div>}<div className="button-row"><button className="button primary" onClick={verify} disabled={checking}><ShieldCheck size={16}/>{checking?'Checking…':'Verify chain'}</button><button className="button secondary" disabled={!chain?.valid||checking} onClick={exportCheckpoint}>Export checkpoint</button></div></section><section className="audit-explanation"><h3>What this verification means</h3><p>It detects changed, reordered or missing events against the stored chain head.</p><p>A database owner could rewrite the entire chain and its head. Keep an exported checkpoint in a separate trusted location to detect that scenario.</p><p>There are no edit or delete endpoints. Revised decisions are new events; earlier decisions remain available.</p><span className="badge neutral">Tamper-evident · not tamper-proof</span></section></div>}
      <footer className="footer"><span><LockKeyhole size={13}/>Synthetic data only · Human review required</span><span><Clock3 size={13}/>Local CPU prototype</span></footer>
    </div></main></div>;
}
